spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fridge_ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false
